"""
Add ambient background music to the silent demo video.

Input:  demo/aletheia_demo_silent.mp4   (generated by make_demo.py)
Output: demo/aletheia_demo.mp4

Music: programmatically synthesised ambient pad (numpy + stdlib wave)
  - Key: D minor  |  Layers: sub-bass drone, pad chords, shimmer arpeggio
  - No external audio files or APIs required

Run:
    cd <repo-root>
    python3 make_demo.py          # generates demo/aletheia_demo_silent.mp4
    python3 demo/add_audio.py     # adds music → demo/aletheia_demo.mp4
"""

import os
import subprocess
import sys
import tempfile
import wave

import numpy as np

ROOT      = os.path.dirname(os.path.abspath(__file__))   # <repo>/demo/
VIDEO_IN  = os.path.join(ROOT, "aletheia_demo_silent.mp4")
OUT       = os.path.join(ROOT, "aletheia_demo.mp4")
SR        = 44100   # sample rate (Hz)

# ── HELPERS ───────────────────────────────────────────────────────────────────
def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        print("CMD:", " ".join(str(c) for c in cmd))
        print("ERR:", r.stderr[-800:])
        sys.exit(1)
    return r

def video_duration(path):
    r = run(["ffprobe", "-v", "error",
             "-show_entries", "format=duration",
             "-of", "default=noprint_wrappers=1:nokey=1", path])
    return float(r.stdout.strip())

def write_wav(samples, path):
    """Write a float32 numpy array in [-1, 1] as stereo 16-bit PCM WAV."""
    pcm = np.clip(samples, -1.0, 1.0)
    pcm16 = (pcm * 32767).astype(np.int16)
    stereo = np.stack([pcm16, pcm16], axis=1)
    with wave.open(path, "w") as wf:
        wf.setnchannels(2)
        wf.setsampwidth(2)
        wf.setframerate(SR)
        wf.writeframes(stereo.tobytes())

# ── MUSIC SYNTHESIS ───────────────────────────────────────────────────────────
def make_music(duration_s: float) -> np.ndarray:
    """
    Synthesise a gentle ambient pad in D minor.

    Three layers:
      1. Sub-bass drone on D1 (36.7 Hz)
      2. Slow pad chords (Dm → F → Am → F) with cross-fades
      3. Shimmer arpeggio in D minor pentatonic at 72 bpm
    """
    n   = int(duration_s * SR)
    t   = np.linspace(0, duration_s, n, endpoint=False)
    out = np.zeros(n)

    # ── 1. Pad chords ──────────────────────────────────────────────────────────
    chord_freqs = [
        [73.4,  110.0, 146.8, 220.0],   # Dm  (D2 A2 D3 A3)
        [87.3,  130.8, 174.6, 261.6],   # F   (F2 C3 F3 C4)
        [110.0, 146.8, 220.0, 293.7],   # Am  (A2 D3 A3 D4)
        [87.3,  130.8, 174.6, 220.0],   # F   (F2 C3 F3 A3)
    ]
    chord_dur = duration_s / len(chord_freqs)

    for ci, freqs in enumerate(chord_freqs):
        s = int(ci * chord_dur * SR)
        e = int((ci + 1) * chord_dur * SR)
        seg_n = e - s
        seg_t = np.linspace(0, chord_dur, seg_n, endpoint=False)

        fade  = min(int(2.0 * SR), seg_n // 2)
        env   = np.ones(seg_n)
        env[:fade]  = np.linspace(0, 1, fade)
        env[-fade:] = np.linspace(1, 0, fade)

        pad = np.zeros(seg_n)
        for freq in freqs:
            for harm, amp in [(1, 0.35), (2, 0.12), (3, 0.06)]:
                detune = 1.0 + np.random.uniform(-0.002, 0.002)
                pad += amp * np.sin(2 * np.pi * freq * harm * detune * seg_t)

        out[s:e] += pad * env * 0.22

    # ── 2. Sub-bass drone ──────────────────────────────────────────────────────
    drone     = 0.08 * np.sin(2 * np.pi * 36.7 * t)
    fi, fo    = int(3.0 * SR), int(3.0 * SR)
    drone_env = np.ones(n)
    drone_env[:fi]  = np.linspace(0, 1, fi)
    drone_env[-fo:] = np.linspace(1, 0, fo)
    out += drone * drone_env

    # ── 3. Shimmer arpeggio ────────────────────────────────────────────────────
    arp_notes = [293.7, 349.2, 440.0, 523.3, 587.3]   # D4 F4 A4 C5 D5
    arp_step  = 60.0 / 72 / 2                          # eighth notes at 72 bpm
    arp_i, pos = 0, 1.5
    while pos < duration_s - 1.0:
        freq   = arp_notes[arp_i % len(arp_notes)]
        start  = int(pos * SR)
        note_n = min(int(arp_step * SR * 0.7), n - start)
        if note_n <= 0:
            break
        st2 = np.arange(note_n) / SR
        a, r2 = min(int(0.02 * SR), note_n), min(int(0.04 * SR), note_n)
        env2  = np.ones(note_n) * 0.6
        env2[:a]  = np.linspace(0, 0.6, a)
        env2[-r2:] = np.linspace(0.6, 0, r2)
        note = np.sin(2 * np.pi * freq * st2) + 0.3 * np.sin(2 * np.pi * freq * 2 * st2)
        out[start:start + note_n] += note * env2 * 0.055
        arp_i += 1
        pos   += arp_step

    # ── Global fade in / out ──────────────────────────────────────────────────
    out[:int(1.5 * SR)]  *= np.linspace(0, 1, int(1.5 * SR))
    out[-int(2.0 * SR):] *= np.linspace(1, 0, int(2.0 * SR))

    return out

# ── MAIN ──────────────────────────────────────────────────────────────────────
def main():
    if not os.path.exists(VIDEO_IN):
        print(f"Error: {VIDEO_IN} not found.")
        print("Run `python3 make_demo.py` from the repo root first.")
        sys.exit(1)

    dur = video_duration(VIDEO_IN)
    print(f"Input:  {VIDEO_IN}  ({dur:.1f}s)")
    print("Synthesising ambient music...")

    music     = make_music(dur + 1.0)
    tmp_music = tempfile.mktemp(suffix=".wav")
    write_wav(music, tmp_music)

    print(f"Mixing into video → {OUT}")
    run([
        "ffmpeg", "-y",
        "-i", VIDEO_IN,
        "-i", tmp_music,
        "-c:v", "copy",
        "-c:a", "aac", "-b:a", "192k",
        "-t", str(dur),
        OUT,
    ])

    os.unlink(tmp_music)
    size_mb = os.path.getsize(OUT) / 1_048_576
    print(f"Done.   {OUT}  ({size_mb:.1f} MB)")

if __name__ == "__main__":
    main()
